# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.10.4
          cache: pip

      - name: Pull Images
        run: |
          pip install -r requirements.txt
          SEESAW="${{secrets.SEESAW_BEARER}}"
          python3 seesaw_pull.py "${{secrets.SEESAW_BEARER}}"
        
      - name: Upload a Reed Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: reed
          path: ./reed
          retention-days: 90

      - name: Upload a Neely Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: neely
          path: ./neely
          retention-days: 90
